Repository wecode-bootcamp-korea/27-2nd-AirPnP-frontend, pull requests merged in 2021-12, with the labels that each got.

#2 [27기 길도연] 라이브러리 추가
  package-lock.json
  package.json
Labels: Status: 리뷰 요청

#4 [27기 길도연] Nav 컴포넌트 구현
  package-lock.json
  package.json
  public/images/peopleicon.jpeg
  src/components/Nav/ExtendedSearchBar/CustomInput/CustomInput.js
  src/components/Nav/ExtendedSearchBar/ExtendedSearchBar.js
  src/components/Nav/ExtendedSearchBar/datepicker.scss
  src/components/Nav/ExtendedSearchBar/mixins.scss
  src/components/Nav/ExtendedSearchBar/variables.scss
  src/components/Nav/Nav.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#5 [27기 이나은] 메인 페이지 레이아웃 구현
  public/image/Main/airpnp-main.jpg
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#6 [27기 길도연] Map 컴포넌트 구현
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/components/Map/CustomMarker/MapLabel.js
  src/components/Map/Map.js
  src/config.js
  src/index.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#3 [27기 김혜리] Add: Login 구현 완료 merge 요청
  .env
  package-lock.json
  public/images/Login/airpnp-Logo.png
  public/images/Login/x-mark.png
  public/index.html
  src/components/Nav/Nav.js
  src/config.js
  src/pages/Login/Login.js
Labels: Status: Accepted

#8 [27기 길도연] 호스트 등록페이지 작성
  package-lock.json
  package.json
  src/Router.js
  src/components/GetPost/GetPost.js
  src/pages/HostRegister/HostRegister.js
  src/pages/HostRegister/HostRegisterEnd/HostRegisterEnd.js
  src/pages/HostRegister/HostRegisterStart/HostRegisterStart.js
  src/pages/HostRegister/HostRegisterStep/AddressSelect/AddressSelect.js
  src/pages/HostRegister/HostRegisterStep/CategorySelect/CategorySelect.js
  src/pages/HostRegister/HostRegisterStep/CategorySelect/TalentList.js
  src/pages/HostRegister/HostRegisterStep/DetailInfo/DetailInfo.js
  src/pages/HostRegister/HostRegisterStep/HostRegisterStep.js
  src/pages/HostRegister/HostRegisterStep/ListCard/ListCard.js
Labels: Status: Accepted

#9 [27기 길도연] 검색창 자동 완성기능 추가
  src/components/Nav/ExtendedSearchBar/AutoCompleteInput/AutoCompleteInput.js
  src/components/Nav/ExtendedSearchBar/AutoCompleteInput/CategoryList.js
  src/components/Nav/ExtendedSearchBar/ExtendedSearchBar.js
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청

#12 [27기 이나은] footer 완성
  src/components/Footer/Footer.js
Labels: Status: 리뷰 요청

#7 [27기 김혜리] Add: 리뷰요청
  package-lock.json
  package.json
  public/Data/ContentBox.json
  public/images/ListPage/cpImage1.png
  public/images/ListPage/nextArrow.png
  public/images/ListPage/prevArrow.png
  public/images/airpnpLogo.png
  src/Router.js
  src/components/Map/Map.js
  src/components/Nav/Nav.js
  src/components/ScrollTop/ScrollTop.js
  src/config.js
  src/index.js
  src/pages/ListPage/Checkbox/Checkbox.js
  src/pages/ListPage/CheckboxShell/CheckboxShell.js
  src/pages/ListPage/CheckboxWrap/CheckboxWrap.js
  src/pages/ListPage/ContentBox/ContentBox.js
  src/pages/ListPage/LeftKeywordButton/LeftKeywordButton.js
  src/pages/ListPage/LikeHeart/LikeHeart.js
  src/pages/ListPage/ListPage.js
  src/pages/ListPage/Pagination/Pagination.js
  src/pages/ListPage/RightKeywordButton/RightKeywordButton.js
  src/pages/ListPage/RightKeywordButton/RightKeywordData.js
  src/pages/ListPage/Slick/Slick.js
Labels: Status: 리뷰 요청

#13 [27기 이나은] footer완성
  src/components/Footer/Footer.js
Labels: Status: 리뷰 요청

#14 [27기 길도연] 호스트 등록페이지 백엔드 통신 로직 구현
  public/images/noimages.png
  src/Router.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/HostRegister/HostRegisterStep/HostImageUpload/HostImageUpload.js
  src/pages/HostRegister/HostRegisterStep/HostRegisterStep.js
Labels: Status: 리뷰 요청

#15 [27기 길도연] 데이트피커 컴포넌트 화
  src/components/DayPicker/CustomInput/CustomInput.js
  src/components/DayPicker/DayPicker.js
  src/components/DayPicker/datepicker.scss
  src/components/DayPicker/mixins.scss
  src/components/DayPicker/variables.scss
  src/components/Nav/ExtendedSearchBar/AutoCompleteInput/AutoCompleteInput.js
  src/components/Nav/ExtendedSearchBar/ExtendedSearchBar.js
Labels: Status: 리뷰 요청

#17 [27기 길도연] Nav 검색 구현
  src/components/DayPicker/CustomInput/CustomInput.js
  src/components/GetPost/GetPost.js
  src/components/Nav/ExtendedSearchBar/ExtendedSearchBar.js
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청

#16 [27기 김혜리] Add: 리스트페이지 완료 - 머지 요청
  package-lock.json
  package.json
  public/Data/ContentBox.json
  src/Router.js
  src/components/Map/Map.js
  src/config.js
  src/pages/ListPage/CheckboxWrap/CheckboxWrap.js
  src/pages/ListPage/ContentBox/ContentBox.js
  src/pages/ListPage/LeftKeywordButton/LeftKeywordButton.js
  src/pages/ListPage/ListPage.js
  src/pages/ListPage/RightKeywordButton/RightKeywordButton.js
  src/pages/ListPage/Slick/Slick.js
Labels: Status: 리뷰 요청

#18 [27기 이나은] ADD: footer수정
  public/Data/detailData.json
  src/pages/HostDetail/DatePickerDetail/DatePickerDetail.js
  src/pages/HostDetail/HostDetail.js
  src/pages/HostDetail/SlickDetail/SlickDetail.js
  src/pages/HostDetail/images.js
Labels: Status: 리뷰 요청

#20 [27기 길도연] 날짜 선택 로직 수정
  src/components/DayPicker/DayPicker.js
  src/components/Nav/ExtendedSearchBar/ExtendedSearchBar.js
  src/config.js
  src/pages/HostDetail/HostDetail.js
  src/pages/HostRegister/HostRegisterStep/CategorySelect/TalentList.js
  src/pages/HostRegister/HostRegisterStep/HostRegisterStep.js
Labels: Status: 리뷰 요청

#22 [27기 길도연] 마커 클릭을 통한 필터링 구현
  src/Router.js
  src/components/Map/CustomMarker/MapLabel.js
  src/components/Map/Map.js
  src/components/Nav/ExtendedSearchBar/CustomInput/CustomInput.js
  src/pages/ListPage/ListPage.js
Labels: Status: Rebase 요청

#21 [27기 길도연] 애니메이션 추가
  src/components/Nav/ExtendedSearchBar/ExtendedSearchBar.js
  src/config.js
Labels: Status: 리뷰 요청

#19 [27기 김혜리] Modified: 컨플릭트 및 머지커밋 해결
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/ListPage/LeftKeywordButton/LeftKeywordButton.js
  src/pages/ListPage/ListPage.js
  src/pages/ListPage/RightKeywordButton/RightKeywordButton.js
  src/pages/ListPage/Slick/Slick.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#23 [27기 길도연] Nav 리렌더링 시 애니메이션 반복되는 문제 해결
  src/components/Nav/ExtendedSearchBar/ExtendedSearchBar.js
Labels: Status: 리뷰 요청

#10 [27기 이나은] 상세페이지 레이아웃 구현
  public/Data/detailData.json
  src/Router.js
  src/components/Map/Map.js
  src/config.js
  src/pages/HostDetail/Data/AdditionInfoListData.js
  src/pages/HostDetail/Data/ArticleData.js
  src/pages/HostDetail/Data/CertificationCellData.js
  src/pages/HostDetail/Data/InfoList.js
  src/pages/HostDetail/HostDetail.js
  src/pages/HostDetail/HostLevelContainer.js
  src/pages/HostDetail/SlickDetail/SlickDetail.js
Labels: Status: 리뷰 요청

#25 Modified: 로그인 모달창 수정
  src/pages/Login/Login.js
Labels: Status: 리뷰 요청

#24 [27기 길도연] 호스트 등록 애니메이션 및 예외처리
  package.json
  src/components/Nav/Nav.js
  src/pages/HostRegister/HostRegisterStep/DetailInfo/DetailInfo.js
  src/pages/HostRegister/HostRegisterStep/HostRegisterStep.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#26 [27기 길도연] Datepicker 기능 추가
  .env
  src/components/DayPicker/DayPicker.js
  src/components/Map/Map.js
  src/pages/HostDetail/HostDetail.js
Labels: Status: 리뷰 요청

#28 Fix: 페이지네이션 수정
  src/config.js
  src/pages/ListPage/ListPage.js
Labels: Status: 리뷰 요청

#29 [27기 길도연] 리드미 수정
  README.md
Labels: Status: Accepted

#30 [27기 길도연] 리드미 수정
  README.md
Labels: Status: Accepted
